---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: generic-parameters
data:
  TZ: Europe/Zurich
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: generic-parameters
  namespace: kube-system
data:
  TZ: Europe/Zurich
